export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const CART_SAVE_USER_ADDRESS = "CART_SAVE_USER_ADDRESS";
export const CART_ORDER_TOTAL_PRICE = "CART_ORDER_TOTAL_PRICE";

export const EMPTY_CART = "EMPTY_CART";
